### ISSUE TITLE
Using fyers we can get live market feed

### ISSUE THREAD

**Issue by raviyellani** [deshwalmahesh/NSE-Stock-Scanner#3]
Using fyers we can get live market feed, can we develop a intraday momentum stock based on this tick data and see which stock is moving up and and down by using your alogs

**Comment by deshwalmahesh** [comment]
This is supposed to be a scanner tool where, given a stock (or stocks) you can have a check if your stock (or any other) is giving you trading signals based on the conditions (strategy) that you have defined. If you are talking about Scalping (Tick by tick data) , I would not recommend using Python  due to network latency, code optimisation and most of all slower execution nature of Python. You could use this tool on 5-15 minutes data easily.

On the other hand, if you have any strategy in mind, you can share the details and I'll put it into code, back test it and check results. You could get a signal anytime those conditions meet  But still you need to put orders by yourself. 

I developed this tool so that people could get hold of historical data, develop strategies ( or use existing ones), back-test them and then apply it out on the real market so if you have any specific strategy, be it scalping, Intra, options, swing or short term investing, please be my guest.
